services:
  job-scraper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    shm_size: '2gb'
    volumes:
      - /tmp:/tmp

